# Generated by Django 3.1.3 on 2022-06-18 10:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(default='', null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True, validators=[app.models.url_validator])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
