# Generated by Django 3.1.3 on 2022-06-18 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220618_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.article')),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.author')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='Comments',
            field=models.ManyToManyField(blank=True, related_name='Comments', to='app.Comments'),
        ),
    ]
