# Generated by Django 3.1.3 on 2022-06-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220618_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.article'),
        ),
    ]
